### ISSUE TITLE
请教一个RSA的问题

### ISSUE THREAD

**Issue by masterJiaxing** [liyu001989/signature#9]
现在有第三方业务给了我一个E和N参数，然后跟我说根据这两个参数去对数据进行RSA加密？请问一下这个要怎么处理？

**Comment by liyu001989** [comment]
这两个参数具体是啥，这个包是用来做签名的，我不知道你具体要实现什么样的业务

**Comment by masterJiaxing** [comment]
主要是根据E,N参数生成rsa公钥，
e:65537, n:24203415747294310969188181196677473189180015883232694331897992185337970984724174889964661734686142805267768430532516147649574549378757622976990391687673741263574415604045694596640413704939511211119016011623133233041299729096088527403699685251283377672476363158842042406791287049291815346890764449215787544235848617866409144293048403007899327310164732937646344190856402667623107035468849322725425370200787519723910903120293050839883706962596024831946423243447310017005002888020741277867370217014788539747015633171227251149153461623580120670517497762045943246419794465045225220295497151333277459232711656463589192676127 
不知道怎么通过这两个参数生成rsa公钥
